# Generated by Django 4.2 on 2023-06-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceDaily",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="시간"),
                ),
                (
                    "is_entering",
                    models.BooleanField(default=False, verbose_name="출입여부"),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=20, verbose_name="비고"),
                ),
            ],
            options={
                "db_table": "attendance_daily",
            },
        ),
        migrations.CreateModel(
            name="AttendanceOverall",
            fields=[
                ("overall_index", models.AutoField(primary_key=True, serialize=False)),
                ("daily_index", models.IntegerField(unique=True)),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="시간"),
                ),
                (
                    "is_entering",
                    models.BooleanField(default=False, verbose_name="출입여부"),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=20, verbose_name="비고"),
                ),
            ],
            options={
                "db_table": "attendance_overall",
            },
        ),
    ]
