# Generated by Django 4.2 on 2023-06-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceDaily",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("is_entering", models.BooleanField(default=False)),
                ("remark", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "attendance_daily",
            },
        ),
        migrations.CreateModel(
            name="AttendanceOverall",
            fields=[
                ("overall_index", models.AutoField(primary_key=True, serialize=False)),
                ("daily_index", models.IntegerField(unique=True)),
                ("timestamp", models.DateTimeField()),
                ("is_entering", models.BooleanField(default=False)),
                ("remark", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "attendance_overall",
            },
        ),
    ]
