# Generated by Django 4.2 on 2023-06-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_academyinfo_classinfo_classtime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendancedaily",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="attendanceoverall",
            old_name="user_id",
            new_name="user",
        ),
    ]
