# Generated by Django 4.2 on 2023-06-29 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_userlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancedaily",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="날짜"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendanceoverall",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="날짜"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendancedaily",
            name="remark",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="비고"
            ),
        ),
        migrations.AlterField(
            model_name="attendancedaily",
            name="timestamp",
            field=models.TimeField(auto_now_add=True, verbose_name="시간"),
        ),
        migrations.AlterField(
            model_name="attendanceoverall",
            name="remark",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="비고"
            ),
        ),
        migrations.AlterField(
            model_name="attendanceoverall",
            name="timestamp",
            field=models.TimeField(verbose_name="시간"),
        ),
    ]
