# Generated by Django 4.2 on 2023-07-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_rename_attendancedaily_attendance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classinfo",
            name="total_days",
            field=models.IntegerField(default=1, max_length=10, verbose_name="총 수강일"),
            preserve_default=False,
        ),
    ]
