# Generated by Django 4.2 on 2023-07-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_classinfo_total_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classinfo",
            name="total_days",
            field=models.IntegerField(verbose_name="총 수강일"),
        ),
    ]
