# Generated by Django 4.2 on 2023-07-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_alter_classinfo_total_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="classinfo",
            name="detail",
            field=models.CharField(
                blank=True, max_length=1055, null=True, verbose_name="상세내용"
            ),
        ),
    ]
