# Generated by Django 4.2 on 2023-06-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=True, verbose_name="스태프 권한"),
        ),
    ]
