# Generated by Django 4.2 on 2023-06-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(upload_to="", verbose_name="프로필 사진"),
        ),
    ]
